# >>>>> varijable
.PHONY:\
	sample

# >>>>> recepti

## >>>>> apstraktni
sample:\
	obrazovne-ustanove_popis_sample.csv

obrazovne-ustanove_popis_sample.csv: obrazovne-ustanove_popis_sample.R
	Rscript $<
